services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3141:3141
    environment:
      PORT: 3141
    env_file:
      ./.local.env
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
    driver: local

