services:
  api:
    profiles: [development]
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    command: bun api dev
    ports:
      - 3142:3142
    environment:
      PORT: 3142
    env_file:
      ./apps/api/.env.development
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres

  api-build:
    profiles: [production]
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: bun api dev
    ports:
      - 3142:3142
    environment:
      PORT: 3142
    env_file:
      ./apps/api/.env.production
    depends_on:
      - postgres

  postgres:
    profiles: [development, production]
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5880
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5880:5880

  api-test:
    profiles: [test]
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    command: bun api test ${API_CMD_ARGS:-''}
    env_file:
      ./apps/api/.env.test
    depends_on:
      - postgres-test
    volumes:
      - .:/app

  api-e2e:
    profiles: [e2e]
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    command: bun api dev
    ports:
      - 3242:3242
    environment:
      PORT: 3242
    env_file:
      ./apps/api/.env.test
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres-test

  postgres-test:
    profiles: [test, e2e]
    image: postgres:16.3-alpine
    attach: false
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5881
    ports:
      - 5881:5881

  client-e2e:
    profiles: [e2e]
    image: oven/bun:1.1
    working_dir: /app
    command: sh -c 'bun i --frozen-lockfile && bun app dev --port 3241'
    environment:
      VITE_API_BASE_URL: ${API_BASE_URL:-http://api-e2e:3242}
    ports:
      - 3241:3241
    volumes:
      - .:/app
    depends_on:
      - api-e2e

  e2e:
    profiles: [e2e]
    build:
      context: .
      dockerfile: ./e2e/Dockerfile
    environment:
      APP_BASE_URL: http://client-e2e:3241
      API_BASE_URL: http://api-e2e:3242
    working_dir: /app
    command: bun e2e test
    ports:
      - 9009:9009
    env_file: ./apps/api/.env.test
    volumes:
      - .:/app
    depends_on:
      - client-e2e
      - api-e2e


volumes:
  postgres-data:
    driver: local

